import { Router, Request, Response } from "express";
import { systemDb, withTenant } from "../db";
import { organizations, jobs } from "../db/schema";
import { eq, and, sql } from "drizzle-orm";
import {
  authenticateJWT,
  authenticateStreamToken,
  authenticateWorker,
  AuthenticatedRequest,
} from "../middleware/auth";
import { sseHub } from "../sse";
import { publishJobEvent } from "../sse/bus";
import { publishJob, QUEUES } from "../queue";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { randomUUID } from "crypto";
import { reserveCredit, refundCredit, InsufficientCredits } from "../credits";
import {
  jobDuration,
  jobGpuSeconds,
  jobQueueWait,
  jobReports,
  jobReportsRejected,
} from "../observability/apiMetrics";
import * as fs from "fs";
import * as path from "path";

const router = Router();

const BUCKET_NAME = process.env.S3_BUCKET_NAME || "medical-image-masks-bucket";
const AWS_REGION = process.env.AWS_REGION || "us-east-1";

const UPLOADS_DIR = path.join(__dirname, "../../../uploads");

// Setup S3 Client (can point to LocalStack, MinIO, or AWS S3)
const s3Client = new S3Client({
  region: AWS_REGION,
  endpoint: process.env.AWS_S3_ENDPOINT || undefined,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || "mock-key-id",
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "mock-secret-key",
  },
  forcePathStyle: true,
});

/**
 * Records how long a job waited between reservation and being claimed.
 *
 * The tier label costs one indexed primary-key lookup per job - not per
 * request - and it is what separates "the standard pool is saturated" from
 * "the tenant we sold a dedicated pool to is queueing", which are different
 * incidents with different responses. Failing to resolve the tier must never
 * fail the claim, so it degrades to an unlabelled observation.
 */
async function recordQueueWait(orgId: string, createdAt: Date | null, startedAt: Date | null) {
  if (!createdAt || !startedAt) return;

  const seconds = (startedAt.getTime() - createdAt.getTime()) / 1000;

  // Both timestamps are generated by the database, so this cannot be negative
  // unless something has gone wrong with the clock behind them. Said out loud
  // rather than dropped: a metric that silently discards its input looks
  // identical to a metric nothing is happening on, which is how the clock skew
  // that motivated this comment stayed hidden.
  if (seconds < 0) {
    console.warn(`Negative queue wait (${seconds}s) for org ${orgId}; check clock sources.`);
    return;
  }

  let tier = "unknown";
  try {
    const org = await systemDb.query.organizations.findFirst({
      where: eq(organizations.id, orgId),
      columns: { infrastructureTier: true },
    });
    if (org) tier = org.infrastructureTier;
  } catch (err) {
    console.error("Could not resolve tier for queue-wait metric:", err);
  }

  jobQueueWait.observe({ tier }, seconds);
}

/* ------------------------------------------------------------------ *
 * Routes with their own authentication, declared before the global
 * Bearer middleware below.
 * ------------------------------------------------------------------ */

// Public Mock upload endpoint (bypasses JWT to behave like S3)
router.put("/mock-upload/:jobId", async (req, res) => {
  const { jobId } = req.params;

  try {
    if (!fs.existsSync(UPLOADS_DIR)) {
      fs.mkdirSync(UPLOADS_DIR, { recursive: true });
    }

    const filePath = path.join(UPLOADS_DIR, `${jobId}-raw.png`);
    const writeStream = fs.createWriteStream(filePath);

    req.pipe(writeStream);

    writeStream.on("finish", () => {
      console.log(`Mock S3 direct-upload completed locally for job ${jobId}`);
      return res.status(200).json({ message: "Mock S3 direct-upload completed successfully" });
    });

    writeStream.on("error", (err) => {
      console.error("Mock upload write error:", err);
      return res.status(500).json({ error: "Mock upload failed writing file" });
    });

  } catch (error) {
    console.error("Mock upload catch error:", error);
    return res.status(500).json({ error: "Mock upload handler failed" });
  }
});

/**
 * SSE Live Events subscription
 * GET /api/jobs/events?token=<stream token>
 *
 * Authenticated by query token rather than Authorization header, because
 * EventSource cannot set headers. Clients mint one via POST /api/auth/stream-token.
 */
router.get("/events", authenticateStreamToken, (req: AuthenticatedRequest, res: Response) => {
  const orgId = req.user!.organizationId;
  const userId = req.user!.id;

  // EventSource resends Last-Event-ID automatically after a dropped connection;
  // the query parameter is the manual equivalent for other clients.
  const rawLastId = req.headers["last-event-id"] ?? req.query.lastEventId;
  const parsed = typeof rawLastId === "string" ? Number(rawLastId) : NaN;
  const lastEventId = Number.isFinite(parsed) && parsed >= 0 ? parsed : null;

  sseHub.addConnection(orgId, userId, res, lastEventId);
});

/**
 * Worker job outcome report
 * POST /api/jobs/:jobId/report
 *
 * The API owns job finalization, credit settlement, and SSE fan-out - the
 * worker only reports what happened. This keeps database credentials out of
 * the GPU tier and keeps every SSE connection in one process.
 */
router.post("/:jobId/report", authenticateWorker, async (req: Request, res: Response) => {
  const { jobId } = req.params;
  const { status, maskImageS3Key, errorMessage, modelVersion, workerId, gpuSeconds } = req.body ?? {};

  if (status !== "PROCESSING" && status !== "SUCCESS" && status !== "FAILED") {
    jobReportsRejected.inc({ reason: "invalid_status" });
    return res.status(400).json({ error: "status must be PROCESSING, SUCCESS or FAILED" });
  }

  // A produced mask must be attributable. Without this the guarantee is only a
  // convention, and one worker deployed without MODEL_VERSION would silently
  // create masks that cannot be traced to the model that generated them.
  if (status === "SUCCESS" && (typeof modelVersion !== "string" || modelVersion.trim() === "")) {
    jobReportsRejected.inc({ reason: "missing_model_version" });
    return res.status(400).json({ error: "modelVersion is required when reporting SUCCESS" });
  }

  // The worker knows a job id and nothing else - it has no organization
  // context to set, so this runs on the RLS-bypassing system identity. It is
  // gated by the worker shared secret and only ever touches the one job.
  try {
    // Interim progress: no credit implications, no transaction needed.
    if (status === "PROCESSING") {
      const [updated] = await systemDb
        .update(jobs)
        // startedAt gives the reaper a clock for execution time, separate from
        // how long the reservation has existed. workerId is recorded at claim
        // time so a job that never completes can still be traced to a machine.
        .set({
          status: "PROCESSING",
          // NOW(), not the API's clock. created_at is generated by the
          // database, so a timestamp taken here is measured against a
          // different clock - and any interval spanning the two is wrong by
          // the skew between them. Locally that skew is the Docker VM running
          // a third of a second ahead of the host, which was enough to make
          // every queue wait come out negative. The same mismatch shifts the
          // reaper's PROCESSING timeout, which compares started_at against
          // NOW() in SQL.
          startedAt: sql`NOW()`,
          workerId: typeof workerId === "string" ? workerId : null,
        })
        .where(and(eq(jobs.id, jobId), eq(jobs.status, "PENDING")))
        .returning();

      if (!updated) {
        jobReportsRejected.inc({ reason: "not_pending" });
        return res.status(409).json({ error: "Job is not PENDING" });
      }

      // Queue wait: reservation to claim. This is the number to autoscale on -
      // it rises before anything else visibly breaks, and unlike queue depth it
      // is denominated in what the customer actually experiences.
      await recordQueueWait(updated.organizationId, updated.createdAt, updated.startedAt);
      jobReports.inc({ status: "PROCESSING" });

      await publishJobEvent(updated.organizationId, "JOB_STATUS_CHANGE", {
        jobId,
        status: "PROCESSING",
      });

      return res.status(200).json({ jobId, status: "PROCESSING" });
    }

    // Terminal states settle the reserved credit, so they run in a transaction
    // with the job row locked.
    const outcome = await systemDb.transaction(async (tx) => {
      const locked = await tx.execute(
        sql`SELECT id, organization_id, status, started_at FROM jobs WHERE id = ${jobId} FOR UPDATE`
      );

      if (locked.rows.length === 0) {
        return { notFound: true as const };
      }

      const row = locked.rows[0] as {
        organization_id: string;
        status: string;
        started_at: string | null;
      };

      // Idempotency guard: a redelivered message must not refund twice.
      if (row.status === "SUCCESS" || row.status === "FAILED") {
        return { alreadyFinal: true as const, status: row.status };
      }

      // completed_at is NOW() for the same reason started_at is: every job
      // timestamp is then on one clock, and the intervals between them mean
      // something.
      let settled: { startedAt: Date | null; completedAt: Date | null } | undefined;

      if (status === "SUCCESS") {
        [settled] = await tx
          .update(jobs)
          .set({
            status: "SUCCESS",
            maskImageS3Key: maskImageS3Key ?? null,
            modelVersion: modelVersion.trim(),
            workerId: typeof workerId === "string" ? workerId : null,
            gpuSeconds: typeof gpuSeconds === "number" ? gpuSeconds : null,
            completedAt: sql`NOW()`,
          })
          .where(eq(jobs.id, jobId))
          .returning({ startedAt: jobs.startedAt, completedAt: jobs.completedAt });
      } else {
        [settled] = await tx
          .update(jobs)
          .set({
            status: "FAILED",
            errorMessage: errorMessage || "Model processing failed",
            // Recorded on failure too: a model version that fails often is
            // exactly what you want to be able to query for.
            modelVersion: typeof modelVersion === "string" ? modelVersion.trim() : null,
            workerId: typeof workerId === "string" ? workerId : null,
            gpuSeconds: typeof gpuSeconds === "number" ? gpuSeconds : null,
            completedAt: sql`NOW()`,
          })
          .where(eq(jobs.id, jobId))
          .returning({ startedAt: jobs.startedAt, completedAt: jobs.completedAt });

        // Reservation is released only on failure. Idempotent: a replayed
        // report cannot refund twice, independently of the status guard above.
        await refundCredit(tx, row.organization_id, jobId, "Refunded after job failure");
      }

      return {
        orgId: row.organization_id,
        startedAt: settled?.startedAt ?? null,
        completedAt: settled?.completedAt ?? null,
      };
    });

    if ("notFound" in outcome) {
      jobReportsRejected.inc({ reason: "not_found" });
      return res.status(404).json({ error: "Job not found" });
    }

    if ("alreadyFinal" in outcome) {
      jobReportsRejected.inc({ reason: "already_final" });
      return res.status(409).json({ error: `Job already finalized as ${outcome.status}` });
    }

    jobReports.inc({ status });

    // Wall-clock execution, which includes anything the worker did around the
    // model - fetching the scan, writing the mask. gpuSeconds below is the
    // model itself, and the gap between the two is where waste hides.
    if (outcome.startedAt && outcome.completedAt) {
      const seconds =
        (outcome.completedAt.getTime() - outcome.startedAt.getTime()) / 1000;
      if (seconds >= 0) jobDuration.observe({ status }, seconds);
    }

    if (typeof gpuSeconds === "number" && Number.isFinite(gpuSeconds)) {
      jobGpuSeconds.observe({ status }, gpuSeconds);
    }

    await publishJobEvent(outcome.orgId, "JOB_STATUS_CHANGE", {
      jobId,
      status,
      maskImageS3Key: status === "SUCCESS" ? maskImageS3Key ?? null : undefined,
      error: status === "FAILED" ? errorMessage : undefined,
    });

    return res.status(200).json({ jobId, status });

  } catch (error) {
    console.error(`Failed to record report for job ${jobId}:`, error);
    return res.status(500).json({ error: "Failed to record job outcome" });
  }
});

/* ------------------------------------------------------------------ *
 * Everything below requires a user session.
 * ------------------------------------------------------------------ */

router.use(authenticateJWT);

/**
 * 1. Request Presigned URL & Reserve Credit (Option A)
 * POST /api/jobs/request
 */
router.post("/request", async (req: AuthenticatedRequest, res: Response) => {
  const orgId = req.user!.organizationId;
  const userId = req.user!.id;

  try {
    // Start transactional credit checking & reservation
    const result = await withTenant(orgId, async (tx) => {
      const jobId = randomUUID();
      const s3Key = `org_id=${orgId}/jobs/${jobId}/raw.png`;

      // The job row is written first so the ledger's job_id foreign key
      // resolves; the reservation below still holds the organization lock for
      // the rest of the transaction, so concurrent spenders remain serialized.
      await tx
        .insert(jobs)
        .values({
          id: jobId,
          organizationId: orgId,
          userId,
          status: "PENDING",
          rawImageS3Key: s3Key,
        })
        .returning();

      // Locks the organization row, writes the ledger entry, and decrements the
      // materialized balance. Throws InsufficientCredits if there is none left.
      await reserveCredit(tx, orgId, jobId);

      return { jobId, s3Key };
    });

    // d. Generate S3 presigned URL for the reserved job
    let presignedUrl = "";
    const isMock = process.env.AWS_ACCESS_KEY_ID === "mock-key-id";

    if (isMock) {
      // Local fallback: mock upload URL
      presignedUrl = `${req.protocol}://${req.get("host")}/api/jobs/mock-upload/${result.jobId}`;
    } else {
      const command = new PutObjectCommand({
        Bucket: BUCKET_NAME,
        Key: result.s3Key,
        ContentType: "image/png",
      });
      presignedUrl = await getSignedUrl(s3Client, command, { expiresIn: 3600 });
    }

    return res.status(200).json({
      jobId: result.jobId,
      s3Key: result.s3Key,
      uploadUrl: presignedUrl,
    });

  } catch (error: any) {
    if (error instanceof InsufficientCredits) {
      return res.status(402).json({ error: "Insufficient organization credits remaining to start a new job." });
    }
    console.error("Queue job request error:", error);
    return res.status(500).json({ error: error.message || "Failed to initiate job" });
  }
});

/**
 * 2. Fetch billing audit logs
 * GET /api/jobs/logs
 */
router.get("/logs", async (req: AuthenticatedRequest, res: Response) => {
  const orgId = req.user!.organizationId;

  // Recall filter: ?modelVersion=<version> answers "which of our scans were
  // produced by this model build?" - the question that matters when a version
  // is withdrawn. Backed by idx_jobs_model_version.
  const modelVersion = typeof req.query.modelVersion === "string" ? req.query.modelVersion : null;

  try {
    const logs = await withTenant(orgId, (tx) =>
      tx.query.jobs.findMany({
        where: modelVersion
          ? and(eq(jobs.organizationId, orgId), eq(jobs.modelVersion, modelVersion))
          : eq(jobs.organizationId, orgId),
        orderBy: (jobs, { desc }) => [desc(jobs.createdAt)],
      })
    );

    return res.status(200).json({ logs });
  } catch (error) {
    return res.status(500).json({ error: "Failed to fetch logs" });
  }
});

/**
 * 3. Trigger job execution (Notify API that S3 upload completed)
 * POST /api/jobs/:jobId/trigger
 */
router.post("/:jobId/trigger", async (req: AuthenticatedRequest, res: Response) => {
  const { jobId } = req.params;
  const orgId = req.user!.organizationId;

  try {
    const found = await withTenant(orgId, async (tx) => {
      const job = await tx.query.jobs.findFirst({
        where: and(
          eq(jobs.id, jobId),
          eq(jobs.organizationId, orgId)
        ),
      });

      const org = await tx.query.organizations.findFirst({
        where: eq(organizations.id, orgId),
      });

      return { job, org };
    });

    const { job, org } = found;

    if (!job) {
      return res.status(404).json({ error: "Job record not found." });
    }

    if (job.status !== "PENDING") {
      return res.status(400).json({ error: `Job has already been dispatched. Current status: ${job.status}` });
    }

    // Determine target queue from the organization's infrastructure tier.
    // One queue per tier, not per tenant - see src/queue/index.ts.
    const queueName = org?.infrastructureTier === "VIP" ? QUEUES.VIP : QUEUES.STANDARD;

    // Publish task message to RabbitMQ queue. The correlation id travels with
    // it, so the worker's log lines and its report back to the API carry the
    // same id as the browser request that dispatched the job.
    await publishJob(queueName, {
      jobId: job.id,
      orgId: orgId,
      s3Key: job.rawImageS3Key,
      requestId: req.requestId,
    });

    return res.status(202).json({
      message: "Job successfully queued for processing",
      jobId: job.id,
      queue: queueName,
    });

  } catch (error) {
    console.error("Failed to trigger job:", error);
    return res.status(500).json({ error: "Failed to queue job message broker execution" });
  }
});

/**
 * 4. Serve a job's raw scan or generated mask
 * GET /api/jobs/:jobId/image/:kind  (kind: raw | mask)
 *
 * Tenant-scoped: the job must belong to the caller's organization. Served
 * behind the normal Bearer session, so the client fetches it as a blob rather
 * than pointing an <img src> straight at it.
 */
router.get("/:jobId/image/:kind", async (req: AuthenticatedRequest, res: Response) => {
  const { jobId, kind } = req.params;
  const orgId = req.user!.organizationId;

  if (kind !== "raw" && kind !== "mask") {
    return res.status(400).json({ error: "Image kind must be 'raw' or 'mask'" });
  }

  try {
    const job = await withTenant(orgId, (tx) =>
      tx.query.jobs.findFirst({
        where: and(eq(jobs.id, jobId), eq(jobs.organizationId, orgId)),
      })
    );

    if (!job) {
      return res.status(404).json({ error: "Job record not found." });
    }

    // jobId comes from a UUID-keyed lookup that just succeeded, so it cannot
    // contain traversal characters by the time we build the path.
    const filePath = path.join(UPLOADS_DIR, `${job.id}-${kind}.png`);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ error: `No ${kind} image stored for this job` });
    }

    res.setHeader("Content-Type", "image/png");
    res.setHeader("Cache-Control", "private, max-age=300");
    return fs.createReadStream(filePath).pipe(res);

  } catch (error) {
    console.error("Failed to serve job image:", error);
    return res.status(500).json({ error: "Failed to read job image" });
  }
});

export default router;
